version: '3.8'

services:
  notes-app:
    build: .
    container_name: notes-app
    ports:
      - "3000:3000"
    volumes:
      - ./notes:/app/notes
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped